### ISSUE TITLE
Некорректное имя проекта

### ISSUE THREAD

**Issue by finomen** [gaudima/PLHomework#1]
CMake Error: The source directory "/home/finomen/cpp_2014/7/HW1-simpleCalc" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by gaudima** [comment]
Не понял в чем суть ошибки. Есть вероятность, что вы перепутали меня с Болотиным Максимом?

**Comment by finomen** [comment]
упс, вероятно да

**Comment by finomen** [comment]
упс, вероятно да
