### ISSUE TITLE
3 - compilation error

### ISSUE THREAD

**Issue by finomen** [gaudima/PLHomework#2]
[100%] Building CXX object CMakeFiles/settings.dir/Settings.cpp.o
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In substitution of ‘template<class _From1, class _To1> static decltype ((__test_aux<_To1>(declval<_From1>()), std::__sfinae_types::__one())) std::__is_convertible_helper<_From, _To, false>::__test(int) [with _From1 = _From1; _To1 = _To1; _From = settings::param; _To = settings::param] [with _From1 = settings::param; _To1 = settings::param]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70:   required from ‘constexpr const bool std::__is_convertible_helper<settings::param, settings::param, false>::value’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<settings::param, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:128:27:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1252:2: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In substitution of ‘template<class _From1, class _To1> static decltype ((__test_aux<_To1>(declval<_From1>()), std::__sfinae_types::__one())) std::__is_convertible_helper<_From, _To, false>::__test(int) [with _From1 = _From1; _To1 = _To1; _From = settings::param; _To = settings::param] [with _From1 = settings::param; _To1 = settings::param]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70:   required from ‘constexpr const bool std::__is_convertible_helper<settings::param, settings::param, false>::value’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<settings::param, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:128:27:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1252:2: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In instantiation of ‘constexpr const bool std::__is_convertible_helper<settings::param, settings::param, false>::value’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<settings::param, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:128:27:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(const _T1&, _U2&&) [with _U2 = settings::param; <template-parameter-2-2> = void; _T1 = const std::basic_string<char>; _T2 = settings::param]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_map.h:458:11:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:131:45: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In substitution of ‘template<class _From1, class _To1> static decltype ((__test_aux<_To1>(declval<_From1>()), std::__sfinae_types::__one())) std::__is_convertible_helper<_From, _To, false>::__test(int) [with _From1 = _From1; _To1 = _To1; _From = const settings::param&; _To = settings::param] [with _From1 = const settings::param&; _To1 = settings::param]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70:   required from ‘constexpr const bool std::__is_convertible_helper<const settings::param&, settings::param, false>::value’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<const settings::param&, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_convertible<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::is_convertible<const settings::param&, settings::param> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:113:38:   required from ‘struct std::__is_direct_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_destructible<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param> >, std::__is_direct_constructible_impl<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:778:12:   required from ‘struct std::__is_direct_constructible_new_safe<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:856:12:   required from ‘struct std::__is_direct_constructible_new<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:864:12:   required from ‘struct std::__is_direct_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:905:12:   required from ‘struct std::__is_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:916:12:   required from ‘struct std::is_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_map.h:579:32:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1252:2: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In substitution of ‘template<class _From1, class _To1> static decltype ((__test_aux<_To1>(declval<_From1>()), std::__sfinae_types::__one())) std::__is_convertible_helper<_From, _To, false>::__test(int) [with _From1 = _From1; _To1 = _To1; _From = const settings::param&; _To = settings::param] [with _From1 = const settings::param&; _To1 = settings::param]’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70:   required from ‘constexpr const bool std::__is_convertible_helper<const settings::param&, settings::param, false>::value’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<const settings::param&, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_convertible<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::is_convertible<const settings::param&, settings::param> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:113:38:   required from ‘struct std::__is_direct_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_destructible<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param> >, std::__is_direct_constructible_impl<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:778:12:   required from ‘struct std::__is_direct_constructible_new_safe<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:856:12:   required from ‘struct std::__is_direct_constructible_new<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:864:12:   required from ‘struct std::__is_direct_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:905:12:   required from ‘struct std::__is_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:916:12:   required from ‘struct std::is_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_map.h:579:32:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1252:2: error: within this context
In file included from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:0:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits: In instantiation of ‘constexpr const bool std::__is_convertible_helper<const settings::param&, settings::param, false>::value’:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1263:12:   required from ‘struct std::is_convertible<const settings::param&, settings::param>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_convertible<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::is_convertible<const settings::param&, settings::param> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:113:38:   required from ‘struct std::__is_direct_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:116:12:   required from ‘struct std::__and_<std::is_destructible<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param> >, std::__is_direct_constructible_impl<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&> >’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:778:12:   required from ‘struct std::__is_direct_constructible_new_safe<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:856:12:   required from ‘struct std::__is_direct_constructible_new<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:864:12:   required from ‘struct std::__is_direct_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char>, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:905:12:   required from ‘struct std::__is_constructible_impl<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:916:12:   required from ‘struct std::is_constructible<std::pair<const std::basic_string<char>, settings::param>, std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, settings::param>&&>’
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_map.h:579:32:   required from ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = std::basic_string<char>; _Tp = settings::param; _Compare = std::lessstd::basic_string<char >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, settings::param> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = settings::param; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char>]’
/home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:55:17:   required from here
/home/finomen/cpp_2014/5/SettingsLib/Settings.h:13:9: error: ‘settings::param::param(const settings::param&)’ is private
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/move.h:57:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_pair.h:61,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/stl_algobase.h:65,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/bits/char_traits.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/ios:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/istream:40,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/fstream:40,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.h:4,
                 from /home/finomen/cpp_2014/5/SettingsLib/Settings.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/include/g++-v4/type_traits:1258:70: error: within this context
make[2]: **\* [CMakeFiles/settings.dir/Settings.cpp.o] Error 1
make[1]: **\* [CMakeFiles/settings.dir/all] Error 2
make: **\* [all] Error 2

**Comment by gaudima** [comment]
Возможно пофиксил ошибки компиляции
